version: "3.7"
services:
  nginx:
    image: nginx:1.23.2
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mysql:
    image: "mysql:8.0.31"
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - db_data:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/fastapi_app
volumes:
  db_data: